# Generated by Django 5.1.5 on 2025-02-11 16:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVArchivingAccessAvailability',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=255)),
                ('name_de', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='Value of the Code. Example https://ddialliance.org/controlled-vocabularies', max_length=255)),
                ('definition', models.TextField(blank=True, help_text='Definition of the Code. Example https://ddialliance.org/controlled-vocabularies')),
            ],
            options={
                'verbose_name': 'Archiving and access: Availability',
                'verbose_name_plural': 'Archiving and access: Availabilities',
                'ordering': ['code', 'name_en'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CVClassificationKeyword',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=255)),
                ('name_de', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('definition', models.TextField(blank=True, help_text='Definition of the Code. See for example https://ddialliance.org/Specification/DDI-CV/ModeOfCollection_3.0.html')),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
                'ordering': ['name_en'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CVGeographicArea',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=2)),
                ('country_name', models.CharField(max_length=255)),
                ('subdivision_code', models.CharField(blank=True, max_length=3)),
                ('subdivision_name', models.CharField(blank=True, max_length=255)),
                ('subdivision_type', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Geographic Area (ISO-3166)',
                'verbose_name_plural': 'Geographic Areas (ISO-3166)',
                'ordering': ['country_code', 'subdivision_code', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CVModeOfCollection',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=255)),
                ('name_de', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='Value of the Code. Example https://ddialliance.org/controlled-vocabularies', max_length=255)),
                ('definition', models.TextField(blank=True, help_text='Definition of the Code. Example https://ddialliance.org/controlled-vocabularies')),
                ('position', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'MD 17 Erhebungsverfahren/Mode of Collection',
                'verbose_name_plural': 'MD 17 Erhebungsverfahren/Modes of Collection',
                'ordering': ['position', 'name_en'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CVResearchFundingAgency',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=255)),
                ('name_de', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='Value of the Code. Example https://ddialliance.org/controlled-vocabularies', max_length=255)),
                ('definition', models.TextField(blank=True, help_text='Definition of the Code. Example https://ddialliance.org/controlled-vocabularies')),
            ],
            options={
                'verbose_name': 'Research Funding Agency',
                'verbose_name_plural': 'Research Funding Agencies',
                'ordering': ['code', 'name_en'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CVSamplingProcedure',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=255)),
                ('name_de', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='Value of the Code. Example https://ddialliance.org/controlled-vocabularies', max_length=255)),
                ('definition', models.TextField(blank=True, help_text='Definition of the Code. Example https://ddialliance.org/controlled-vocabularies')),
                ('position', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'MD 16 Auswahlverfahren/SamplingProcedure',
                'verbose_name_plural': 'MD 16 Auswahlverfahren/SamplingProcedures',
                'ordering': ['position', 'name_en'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CVSubjectArea',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=255)),
                ('name_de', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='Value of the Code. Example https://ddialliance.org/controlled-vocabularies', max_length=255)),
                ('definition', models.TextField(blank=True, help_text='Definition of the Code. Example https://ddialliance.org/controlled-vocabularies')),
            ],
            options={
                'verbose_name': 'MD 09 Fachgebiet/Subject area',
                'verbose_name_plural': 'MD 09 Fachgebiete/Subject areas',
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CVTimeDimension',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=255)),
                ('name_de', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('code', models.CharField(blank=True, help_text='Value of the Code. Example https://ddialliance.org/controlled-vocabularies', max_length=255)),
                ('definition', models.TextField(blank=True, help_text='Definition of the Code. Example https://ddialliance.org/controlled-vocabularies')),
                ('position', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'MD 14 Typ Forschungsdesign/Time Dimension',
                'verbose_name_plural': 'MD 14 Typen Forschungsdesign/Time Dimensions',
                'ordering': ['position', 'name_en'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Filetype',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('extension', models.CharField(help_text='File extension, including the leading dot. E.g.: `.txt`.', max_length=255)),
                ('software', models.CharField(blank=True, help_text='Software used to create the file.', max_length=255)),
            ],
            options={
                'verbose_name': 'Filetype',
                'verbose_name_plural': 'Filetypes',
            },
        ),
    ]
