# Generated by Django 5.2.1 on 2025-05-12 21:31

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classification', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='filetype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('extension'), django.db.models.functions.text.Lower('software'), name='unique_lower_extension_software', violation_error_message='This combination of file extension and software already exists (case-insensitive).'),
        ),
    ]
