# SPDX-FileCopyrightText: Thomas Breitner
#
# SPDX-License-Identifier: CC0-1.0

repos:
  - repo: https://github.com/fsfe/reuse-tool
    rev: v5.0.2
    hooks:
     - id: reuse
  # - repo: https://github.com/astral-sh/ruff-pre-commit
  #   rev: v0.9.6
  #   hooks:
  #     - id: ruff
  #     - id: ruff-format
