# Generated by Django 5.2.1 on 2025-05-13 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='curators',
            field=models.ManyToManyField(blank=True, help_text='Data curators are the people within the research project who are responsible for maintaining and managing the metadata. There is usually only one, but there may be more.', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resource',
            name='datacite_resource_type_general',
            field=models.CharField(blank=True, choices=[('Audiovisual', 'Audiovisual'), ('Award', 'Award'), ('Book', 'Book'), ('BookChapter', 'Bookchapter'), ('Collection', 'Collection'), ('ComputationalNotebook', 'Computationalnotebook'), ('ConferencePaper', 'Conferencepaper'), ('ConferenceProceeding', 'Conferenceproceeding'), ('DataPaper', 'Datapaper'), ('Dataset', 'Dataset'), ('Dissertation', 'Dissertation'), ('Event', 'Event'), ('Image', 'Image'), ('Instrument', 'Instrument'), ('InteractiveResource', 'Interactiveresource'), ('Journal', 'Journal'), ('JournalArticle', 'Journalarticle'), ('Model', 'Model'), ('Other', 'Other'), ('OutputManagementPlan', 'Outputmanagementplan'), ('PeerReview', 'Peerreview'), ('PhysicalObject', 'Physicalobject'), ('Preprint', 'Preprint'), ('Project', 'Project'), ('Report', 'Report'), ('Service', 'Service'), ('Software', 'Software'), ('Sound', 'Sound'), ('Standard', 'Standard'), ('StudyRegistration', 'Studyregistration'), ('Text', 'Text'), ('Workflow', 'Workflow')], default='Dataset', help_text='DataCite Metadata 10.a. Default value is `Dataset`', max_length=50, verbose_name='DataCite ResourceTypeGeneral'),
        ),
    ]
