# Generated by Django 5.1.5 on 2025-02-11 16:47

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import rdml.organization.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='ACME Institute', max_length=255)),
                ('organization_abbr', models.CharField(default='ACME', max_length=255, verbose_name='Organization abbreviation')),
                ('organization_logo', models.FileField(blank=True, help_text='Logo file (SVG)', null=True, upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='Logo file')),
                ('organization_figurative_mark', models.FileField(blank=True, null=True, upload_to='branding/', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='Figurative Mark/"Bildmarke"')),
                ('organization_affiliation', models.CharField(blank=True, help_text='E.g. the name of a higher-level institution. Displayed in the footer of the website.', max_length=255, verbose_name='Affiliation')),
            ],
            options={
                'verbose_name': 'Branding',
                'verbose_name_plural': 'Branding',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('abbr', models.CharField(blank=True, help_text='Abbreviation for this Organization', max_length=255)),
                ('url', models.URLField(blank=True)),
                ('ror_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_en', models.CharField(help_text='The name of the entity that holds, archives, publishes prints, distributes, releases, issues, or produces the resource.', max_length=255)),
                ('abbr_en', models.CharField(blank=True, help_text='Abbreviation for this publisher', max_length=255)),
                ('url', models.URLField(blank=True)),
                ('ror_id', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationalUnit',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('abbr', models.CharField(blank=True, help_text='Abbreviation for this Organizational Unit.', max_length=255)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_ou_name'), models.UniqueConstraint(django.db.models.functions.text.Lower('slug'), name='unique_ou_slug')],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('name_slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('cone_id', models.CharField(blank=True, help_text='PuRe Person CoNE ID, eg: `persons123456`', max_length=13, null=True, validators=[rdml.organization.models.validate_coneid], verbose_name='PuRe person CoNE ID')),
                ('orcid_id', models.URLField(blank=True, help_text='Format: full https URI: https://orcid.org/xxxx-xxxx-xxxx-xxxx, complete with the protocol (https://), and with hyphens in the identifier (xxxx-xxxx-xxxx-xxxx).', null=True, validators=[rdml.organization.models.validate_orcid], verbose_name='ORCID ID')),
                ('gnd_id', models.CharField(blank=True, help_text='Gemeinsame Normdatei, eg: `13015461X`', max_length=10, null=True, verbose_name='GND ID')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='organization.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='unique_email'), models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_name'), models.UniqueConstraint(django.db.models.functions.text.Lower('cone_id'), name='unique_coneid'), models.UniqueConstraint(django.db.models.functions.text.Lower('orcid_id'), name='unique_orcid')],
            },
        ),
    ]
