# Generated by Django 5.1.6 on 2025-02-13 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='abbr',
            field=models.CharField(blank=True, help_text='Abbreviation for this Organization', max_length=255, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='ror_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ROR ID'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='abbr',
            field=models.CharField(blank=True, help_text='Abbreviation for this Organizational Unit.', max_length=255, verbose_name='Abbreviation'),
        ),
        migrations.AlterField(
            model_name='organizationalunit',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='abbr_en',
            field=models.CharField(blank=True, help_text='Abbreviation for this publisher', max_length=255, verbose_name='Abbreviation (EN)'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='ror_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ROR ID'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
    ]
