# Generated by Django 5.2.1 on 2025-05-14 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organization_abbr_alter_organization_ror_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name_slug', 'last_name', 'first_name']},
        ),
    ]
