# Generated by Django 5.2.9 on 2025-12-19 15:28

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_person_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
        migrations.AlterModelOptions(
            name='organizationalunit',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
    ]
