# Generated by Django 5.1.5 on 2025-02-11 16:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCiteConfiguration',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False, help_text='Only one DataCiteConfiguration can be active at a time.')),
                ('note', models.TextField(blank=True)),
                ('datacite_instance', models.CharField(choices=[('TEST', 'Test'), ('PROD', 'Production')], default='TEST', help_text='DataCite instance to use. This sets the DataCite Fabrica and API base URLs.', max_length=10)),
                ('doi_prefix', models.CharField(default='10.12345', max_length=100, verbose_name='DOI Prefix')),
                ('repo_id', models.CharField(default='ABCD.EFGHIJ', help_text='The Repository ID is a unique identifier for each repository in DataCite. It must contain only upper case letters and numbers, and must start with the Member ID.', max_length=100, verbose_name='Repository ID')),
                ('backend_password', models.CharField(default='datacite-secret', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataCiteResource',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doi', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='DOI')),
                ('citation_snippet', models.TextField(blank=True)),
                ('datacite_history', models.JSONField(blank=True, default=list, help_text='Collects API responses from DataCite.')),
                ('resource', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.resource')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('doi', None), ('resource__isnull', False)), models.Q(('doi__isnull', False), ('resource__isnull', False)), _connector='OR'), name='doimanager_dataciteresource_resource_and_doi_cannot_be_null')],
            },
        ),
    ]
