# Generated by Django 5.1.6 on 2025-02-13 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doimanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataciteconfiguration',
            options={'verbose_name': 'DataCite Configuration', 'verbose_name_plural': 'DataCite Configurations'},
        ),
    ]
