# Generated by Django 5.1.6 on 2025-02-13 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doimanager', '0002_alter_dataciteconfiguration_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataciteresource',
            options={'permissions': [('register_or_update_dois', 'Can register and update DOI records')]},
        ),
    ]
