# Generated by Django 5.2.1 on 2025-06-04 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doimanager', '0003_alter_dataciteresource_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataciteresource',
            options={'ordering': ['-updated', '-created'], 'permissions': [('register_or_update_dois', 'Can register and update DOI records')]},
        ),
    ]
