# Generated by Django 5.2.9 on 2025-12-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doimanager', '0004_alter_dataciteresource_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataciteconfiguration',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only one DataCiteConfiguration can be active at a time.'),
        ),
    ]
